---
version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news_miner
    expose: 
      - 5500
    env_file:
      - .env
    networks:
      - proxy
networks:
  proxy:
   external: true