---
version: "3.7"
services:
  redis:
    image: redis:7.0.15
    container_name: scrape_redis
    expose:
      - ${REDIS_PORT}
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./redis_data:/data\
    command: redis-server --requirepass ${REDIS_PASS}
    restart: always
    networks:
      - proxy
  
  backend:
    depends_on:
      - redis
    image: ${IMAGE_URL}
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: news_miner
    restart: unless-stopped
    # ports:
    #   - 5500:5500
    expose: 
      - 8694
    env_file:
      - .env
    networks:
      - proxy
networks:
  proxy:
   external: true