name: Docker Image Upload

# branch master일 때만 액션 실행
on:
  push:
    branches: [ "master" ]

jobs:
  push-image-to-docker-hub:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version)
     
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: private registry login
      uses: docker/login-action@v2
      with:
        registry: registry.donghyuns.com
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: dockerfile build and push
      run: |
        docker build . --file Dockerfile --tag registry.donghyuns.com/${{secrets.IMAGE_NAME}}/${{secrets.PROJ_NAME}}:latest
        docker push registry.donghyuns.com/${{secrets.IMAGE_NAME}}/${{secrets.PROJ_NAME}}:latest